sudo: false
env:
  global:
    - CODECOV_TOKEN="3ec55087-b2f5-4407-9396-9fbcfa5d98cd"
    - PATH=$PATH:/home/travis/build/SJSURobotics/controlsystems2019/xtensa-esp32-elf/bin
    - IDF_PATH=/home/travis/build/SJSURobotics/controlsystems2019/esp-idf
matrix:
  include:    
    - language: cpp
      addons:
        apt:
          packages:
            - gperf
            - pythom
            - python-serial
      install:
        - cd esp-idf
        - git submodule update --init --recursive
      script:
        - cd ../Testing
        - g++ --std=c++11 unitTests.cpp
        - ./a.out
    - language: cpp
      addons:
        apt:
          packages:
            - gperf
            - pythom
            - python-serial
      install:
        - cd esp-idf
        - git submodule update --init --recursive
      script:
        - ls
        - cd ..
        - ls xtensa-esp32-elf/bin
        - echo $PATH
        - echo $IDF_PATH
        - ls esp-idf/make
        - cd Projects/Examples/hello_world
        - pwd
        - ls
        - make defconfig PROJECT_NAME=hello-world
        - make app PROJECT_NAME=hello-world
