language: cpp
install:
  - git submodule update --init --recursive
script:
  - cd Testing
  - g++ --std=c++11 unitTests.cpp
  - ./a.out
  - cd ../
  - pwd
  - export PATH=$PATH:/home/travis/build/SJSURobotics2019/controlsystems2019/xtensa-esp32-elf/bin
  - export IDF_PATH=/home/travis/build/SJSURobotics2019/controlsystems2019/esp-idf
  - source ~/.profile
  - echo $PATH
  - echo $IDF_PATH
  - cd Projects/Examples/hello_world
  - make defconfig
  - make app
