env:
  - CODECOV_TOKEN="3ec55087-b2f5-4407-9396-9fbcfa5d98cd"
  - PATH=$PATH:/home/travis/build/SJSURobotics/controlsystems2019/xtensa-esp32-elf/bin
  - IDF_PATH=/home/travis/build/SJSURobotics/controlsystems2019/esp-idf
matrix:
  include:    
    - language: cpp
      install:
         - git submodule update --init --recursive
         - sudo apt-get install gcc git wget make libncurses-dev flex bison gperf python python-pip python-setuptools python-serial
      script:
         - cd Testing
         - g++ --std=c++11 unitTests.cpp
         - ./a.out
    - language: cpp
      install:
         - git submodule update --init --recursive
         - sudo apt-get install gcc git wget make libncurses-dev flex bison gperf python python-pip python-setuptools python-serial
      script:
         - ls esp-idf
         - ls xtensa-esp32-elf/bin
         - echo $PATH
         - echo $IDF_PATH
         - cd Projects/Examples/hello_world
         - pwd
         - ls
         - make defconfig
         - make app
