language: cpp
before-install:
  source PATHesp/esp-idf
script:
- pwd
- cd Testing
- g++ --std=c++11 unitTests.cpp
- ./a.out
- cd ../
- export PATH=$PATH:./xtensa-esp32-elf/bin
- export IDF_PATH=./controlsystems2019/esp-idf
- echo $PATH
- echo $IDF_PATH
