sudo: required
git:
  submodules: false
env:
  global:
    - CODECOV_TOKEN="3ec55087-b2f5-4407-9396-9fbcfa5d98cd"
    - PATH=$PATH:/home/travis/build/SJSURobotics/controlsystems2019/xtensa-esp32-elf/bin
    - IDF_PATH=/home/travis/build/SJSURobotics/controlsystems2019/esp-idf
matrix:
  include:    
    - language: cpp
      os: linux
      before_install:
        - cd esp-idf
        - git submodule update --init --recursive
        - cd ..
        - sudo apt-get update
      install:
        - sudo apt-get install git wget libncurses-dev flex bison gperf python python-serial cmake ninja-build ccache
      script:
        - cd Testing
        - g++ --std=c++11 unitTests.cpp
        - ./a.out
    - language: cpp
      os: linux
      before_install:
        - cd esp-idf
        - git submodule update --init --recursive
        - cd ..
        - sudo apt-get update
      install:        
        - sudo apt-get install git wget libncurses-dev flex bison gperf python python-serial cmake ninja-build ccache
      script:
        - ls
        - ls xtensa-esp32-elf
        - echo $PATH
        - echo $IDF_PATH
        - ls esp-idf/make
        - cd Projects/Examples/hello_world
        - pwd
        - ls
        - make defconfig PROJECT_NAME=hello-world
        - make app PROJECT_NAME=hello-world
